### ISSUE TITLE
change metaphor so it delivers to mgmt cluster namespaces

### ISSUE THREAD

**Issue by johndietz** [kubefirst/gitops-template#763]
for simplicity of the kubefirst oss / kubefirst pro story, we should have metaphor delivering to namespaces in the management cluster by default, with docs to describe how to bind those instances to new clusters.

**Comment by CristhianF7** [comment]
Metaphor implementation was fixed in: https://github.com/kubefirst/gitops-template/pull/777. 
Still missing the docs
