### ISSUE TITLE
complete physical cluster management in google cloud

### ISSUE THREAD

**Issue by johndietz** [kubefirst/gitops-template#765]

**Comment by jarededwards** [comment]
we never finished implementing physical cluster management in google cloud but spiked a decent bit. 

a few assumptions upfront for mvp:
 - the new physical cluster can come up in the same gcp project
 - it can have administrative credentials the same as the "management" cluster creation
 - crossplane should do the provisioning with the terraform provider the same as the other clouds
 
digitalocean is a good template to look at how we implemented physical clusters with remote modules for [workload clusters](https://github.com/kubefirst/gitops-template/tree/main/digitalocean-github/terraform/digitalocean/modules/workload-cluster) (civo needs to adopt this new remote terraform pattern in favor of inline) the api code that is repsonsible lives in [kubefirst-api-ee](https://github.com/kubefirst/kubefirst-api-ee/blob/main/internal/services/cluster.go#L395)
